
ifneq (native, $(BOARD))
    FEATURES_REQUIRED += periph_flashpage
    FEATURES_REQUIRED += periph_gpio_irq
    USEMODULE += periph_flashpage_pagewise
endif

USEMODULE += ctap_trans
EXTERNAL_MODULE_DIRS += $(CURDIR)/ctap/trans
INCLUDES += -I$(CURDIR)/ctap/trans/include

USEPKG += tinycbor

USEPKG += relic
INCLUDES += -I$(PKGDIRBASE)/relic/src/bc
# The rest of the parameters are configuration parameters for RELIC described in its documentation.
export RELIC_CONFIG_FLAGS=-DARCH=NONE -DOPSYS=NONE -DQUIET=off -DWORD=32 -DFP_PRIME=256 -DWITH="BN;MD;DV;FP;EP;CP;BC;EC" -DSEED=RIOTRND

USEMODULE += crypto_aes
USEMODULE += cipher_modes
USEMODULE += hashes
USEMODULE += fmt
USEMODULE += xtimer
